#!/bin/bash

# Get current folder name
FOLDER=${PWD##*/}

#echo "This command is depreacted. Use metabox/shell instead."
#exit 1

# Check we are in the right place
if [ ! -f ./.JRCyC8oOiO.metabox ]; then
    echo "You cannot run this script form here, please run it in MetaBox's root folder."
    exit 1
fi

if [[ $# -eq 0 ]] ; then
    echo "You must specify a service or service,instance."
    exit 1
else
    Reyns/reyns ssh:$@,command="sudo -i -u metauser bash"
fi
